spring.application.name=backend

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raizes_nordeste
spring.datasource.username=postgres
spring.datasource.password=321598

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:trocar antes de publicar- min 32bytes}
jwt.expiration-ms=3600000

spring.jackson.serialization.write-dates-as-timestamps=false