spring.application.name=backend

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raizes_nordeste
spring.datasource.username=postgres
spring.datasource.password=321598

spring.jpa.hibernate.ddl-auto=update