CREATE TABLE usuario (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(255) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    senha_hash  VARCHAR(255) NOT NULL,
    perfil      VARCHAR(255) NOT NULL,
    criado_em   TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('CLIENTE', 'ATENDENTE', 'GERENTE', 'ADMIN'))
);

CREATE TABLE unidade (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome    VARCHAR(255) NOT NULL,
    cidade  VARCHAR(255) NOT NULL,
    estado  VARCHAR(255) NOT NULL,
    tipo    VARCHAR(255) NOT NULL,
    CONSTRAINT ck_unidade_tipo CHECK (tipo IN ('COMPLETA', 'REDUZIDA'))
);

CREATE TABLE produto (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(255) NOT NULL,
    descricao  VARCHAR(255),
    preco      NUMERIC(10, 2) NOT NULL,
    categoria  VARCHAR(255),
    CONSTRAINT ck_produto_preco CHECK (preco > 0)
);

CREATE TABLE estoque (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unidade_id  BIGINT NOT NULL,
    produto_id  BIGINT NOT NULL,
    quantidade  INTEGER NOT NULL,
    CONSTRAINT fk_estoque_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id),
    CONSTRAINT fk_estoque_produto FOREIGN KEY (produto_id) REFERENCES produto (id),
    CONSTRAINT uk_estoque_unidade_produto UNIQUE (unidade_id, produto_id),
    CONSTRAINT ck_estoque_quantidade CHECK (quantidade >= 0)
);

CREATE TABLE pedido (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    BIGINT NOT NULL,
    unidade_id    BIGINT NOT NULL,
    canal_pedido  VARCHAR(255) NOT NULL,
    status        VARCHAR(255) NOT NULL,
    total         NUMERIC(10, 2) NOT NULL,
    criado_em     TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES usuario (id),
    CONSTRAINT fk_pedido_unidade FOREIGN KEY (unidade_id) REFERENCES unidade (id),
    CONSTRAINT ck_pedido_canal CHECK (canal_pedido IN ('APP', 'TOTEM', 'BALCAO', 'PICKUP', 'WEB')),
    CONSTRAINT ck_pedido_status CHECK (status IN ('AGUARDANDO_PAGAMENTO', 'EM_PREPARO', 'PRONTO',
                                                  'ENTREGUE', 'CANCELADO', 'PAGAMENTO_RECUSADO')),
    CONSTRAINT ck_pedido_total CHECK (total >= 0)
);

CREATE TABLE item_pedido (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id       BIGINT NOT NULL,
    produto_id      BIGINT NOT NULL,
    quantidade      INTEGER NOT NULL,
    preco_unitario  NUMERIC(10, 2) NOT NULL,
    CONSTRAINT fk_item_pedido_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    CONSTRAINT fk_item_pedido_produto FOREIGN KEY (produto_id) REFERENCES produto (id),
    CONSTRAINT ck_item_pedido_quantidade CHECK (quantidade > 0),
    CONSTRAINT ck_item_pedido_preco CHECK (preco_unitario >= 0)
);

CREATE TABLE pagamento (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id        BIGINT NOT NULL,
    status           VARCHAR(255) NOT NULL,
    forma_pagamento  VARCHAR(255) NOT NULL,
    criado_em        TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_pagamento_pedido FOREIGN KEY (pedido_id) REFERENCES pedido (id),
    CONSTRAINT uk_pagamento_pedido UNIQUE (pedido_id),
    CONSTRAINT ck_pagamento_status CHECK (status IN ('PENDENTE', 'APROVADO', 'RECUSADO'))
);

CREATE TABLE audit_log (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_email  VARCHAR(255) NOT NULL,
    acao           VARCHAR(255) NOT NULL,
    entidade       VARCHAR(255) NOT NULL,
    entidade_id    BIGINT,
    detalhes       TEXT,
    criado_em      TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_pedido_cliente      ON pedido (cliente_id);
CREATE INDEX idx_pedido_canal        ON pedido (canal_pedido);
CREATE INDEX idx_pedido_status       ON pedido (status);
CREATE INDEX idx_item_pedido_pedido  ON item_pedido (pedido_id);
CREATE INDEX idx_audit_log_entidade  ON audit_log (entidade, entidade_id);
